# netlify.toml
[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
  included_files = [
    "node_modules/sharp/**/*",
    "node_modules/@img/sharp-*/**/*"
  ]

[functions]
  node_bundler = "esbuild"

[[scheduled.functions]]
  name = "generate-weekly-summaries"
  cron = "0 * * * *"
