# netlify.toml

[build]
  command = "next build"
  publish = ".next"            # Netlify Next.js Runtime uses this

[build.environment]
  NODE_VERSION = "20"          # or "20" if your app needs it

[[plugins]]
  package = "@netlify/plugin-nextjs"
